// <auto-generated />
using Authn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authn.Data
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20220830101033_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Authn.Data.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameIdentifier")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "bob@admonex.com",
                            Firstname = "Bob",
                            Lastname = "Tester",
                            Mobile = "800-555-1212",
                            Password = "pizza",
                            Provider = "Cookies",
                            Roles = "Admin",
                            Username = "bob"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
